# Generated by Django 5.2.1 on 2025-05-13 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Father_name',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Mother_name',
            new_name='mother_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Standard',
            new_name='standard',
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
