# Generated by Django 5.2.1 on 2025-05-13 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_address_student_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='username',
        ),
    ]
