# Generated by Django 5.2.1 on 2025-05-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_name_student_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='username',
            new_name='name',
        ),
    ]
